#!/usr/bin/env bash
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*" >&2; }

CONFIG_DIRS=(/config /config/claude /config/t3 /config/gh /config/git /config/jj
  /config/shell /config/shell/bashrc.d /config/ssh)
CACHE_DIRS=(/cache /cache/go /cache/go/pkg /cache/go/pkg/mod /cache/go/build /cache/go/bin
  /cache/cargo /cache/uv /cache/uv/python /cache/npm /cache/fnm
  /cache/fnm/node-versions /cache/fnm/aliases /cache/npm-global)

WORKSPACE="${WORKSPACE:-/workspace}"

as_code() { gosu code "$@"; }

root_half() {
  local puid="${PUID:-1000}" pgid="${PGID:-1000}"

  if [ "$(id -g code)" != "$pgid" ]; then
    log "remapping group code to gid $pgid"
    groupmod -o -g "$pgid" code
    usermod -g "$pgid" code
  fi
  if [ "$(id -u code)" != "$puid" ]; then
    log "remapping user code to uid $puid"
    usermod -o -u "$puid" code
  fi
  # usermod only fixes files inside $HOME; npm prefix must stay writable for `npm -g`
  if [ -d /opt/npm-global ]; then
    chown "$puid:$pgid" /opt/npm-global /opt/npm-global/bin /opt/npm-global/lib \
      /opt/npm-global/lib/node_modules 2>/dev/null || true
  fi

  local d
  for d in "${CONFIG_DIRS[@]}" "${CACHE_DIRS[@]}"; do
    mkdir -p "$d"
    if ! as_code test -w "$d"; then
      log "chown -R $puid:$pgid $d"
      chown -R "$puid:$pgid" "$d"
    fi
  done

  if [ ! -d "$WORKSPACE" ]; then
    if mkdir -p "$WORKSPACE" 2>/dev/null; then
      chown "$puid:$pgid" "$WORKSPACE"
    else
      log "warning: workspace $WORKSPACE does not exist and cannot be created"
    fi
  elif [ "$(stat -c %u "$WORKSPACE")" = 0 ] && [ -z "$(ls -A "$WORKSPACE")" ]; then
    # fresh named volume; never touch a populated bind mount
    chown "$puid:$pgid" "$WORKSPACE"
  elif ! as_code test -w "$WORKSPACE"; then
    log "warning: workspace $WORKSPACE not writable by uid $puid; fix ownership on the host"
  fi

  [ "${KEYRING:-0}" = 1 ] && prepare_keyring_env "$puid" "$pgid"
  write_profile_env
  [ "${SSHD:-0}" = 1 ] && start_sshd

  exec gosu code "$0" "$@"
}

# ssh sessions do not inherit the container env. Login shells source the
# profile.d file; sshd applies ~/.ssh/environment to every session type.
HARNESS_ENV_VARS=(WORKSPACE NODE_VERSION CLAUDE_CONFIG_DIR T3CODE_HOME GH_CONFIG_DIR
  GIT_CONFIG_GLOBAL JJ_CONFIG HISTFILE GOPATH GOMODCACHE GOCACHE CARGO_HOME
  RUSTUP_HOME UV_CACHE_DIR UV_PYTHON_INSTALL_DIR NPM_CONFIG_CACHE
  NPM_CONFIG_PREFIX FNM_DIR AUTO_UPDATE_PREFIX DISABLE_AUTOUPDATER CHROME_PATH
  PUPPETEER_SKIP_DOWNLOAD PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
  T3CODE_HOST T3CODE_PORT T3CODE_CLOUDFLARED_PATH
  XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS)

write_profile_env() {
  local v
  {
    echo '# generated by entrypoint'
    for v in "${HARNESS_ENV_VARS[@]}"; do
      [ -n "${!v:-}" ] && printf 'export %s=%q\n' "$v" "${!v}"
    done
  } > /etc/profile.d/harness-env.sh
  {
    for v in "${HARNESS_ENV_VARS[@]}" PATH; do
      [ -n "${!v:-}" ] && printf '%s=%s\n' "$v" "${!v}"
    done
  } > /config/ssh/environment
  chown "${PUID:-1000}:${PGID:-1000}" /config/ssh/environment
}

start_sshd() {
  local keys=/config/ssh/host_keys
  mkdir -p "$keys" /run/sshd
  [ -f "$keys/ssh_host_ed25519_key" ] || ssh-keygen -q -t ed25519 -N '' -f "$keys/ssh_host_ed25519_key"
  chmod 0600 "$keys/ssh_host_ed25519_key"
  touch /config/ssh/authorized_keys
  chown "${PUID:-1000}:${PGID:-1000}" /config/ssh/authorized_keys
  chmod 0600 /config/ssh/authorized_keys
  if /usr/sbin/sshd -t -f /etc/ssh/sshd_harness.conf; then
    /usr/sbin/sshd -f /etc/ssh/sshd_harness.conf
    log "sshd listening on 22 (user code, keys from /config/ssh/authorized_keys)"
  else
    log "warning: sshd config test failed, not starting sshd"
  fi
}

# Fixed bus address so ssh sessions and docker exec login shells can find it.
prepare_keyring_env() {
  export XDG_RUNTIME_DIR="/run/user/$1"
  export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
  mkdir -p "$XDG_RUNTIME_DIR"
  chown "$1:$2" "$XDG_RUNTIME_DIR"
  chmod 0700 "$XDG_RUNTIME_DIR"
}

# Throwaway keyring: empty password, unlocked for the container's lifetime.
start_keyring() {
  export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-$(id -u)}"
  export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=$XDG_RUNTIME_DIR/bus}"
  mkdir -p "$XDG_RUNTIME_DIR"
  chmod 0700 "$XDG_RUNTIME_DIR"
  # stale socket from a previous run of this container
  rm -f "${DBUS_SESSION_BUS_ADDRESS#unix:path=}"
  if ! dbus-daemon --session --address="$DBUS_SESSION_BUS_ADDRESS" --fork --nopidfile; then
    log "warning: dbus-daemon failed, keyring not available"
    unset DBUS_SESSION_BUS_ADDRESS
    return 0
  fi
  if printf '' | gnome-keyring-daemon --unlock --components=secrets >/dev/null; then
    log "Secret Service running on $DBUS_SESSION_BUS_ADDRESS (throwaway keyring, empty password)"
  else
    log "warning: gnome-keyring-daemon failed, keyring not available"
  fi
}

link_ssh() {
  chmod 0700 /config/ssh
  if [ -L "$HOME/.ssh" ]; then
    ln -sfn /config/ssh "$HOME/.ssh"
  elif [ -d "$HOME/.ssh" ]; then
    rmdir "$HOME/.ssh" 2>/dev/null || { log "warning: $HOME/.ssh is a non-empty dir, not linking /config/ssh"; return 0; }
    ln -s /config/ssh "$HOME/.ssh"
  else
    ln -sfn /config/ssh "$HOME/.ssh"
  fi
}

link_fnm_node() {
  local fnm_dir="${FNM_DIR:-/cache/fnm}" node_version="${NODE_VERSION:-}" inst
  if [ -z "$node_version" ]; then
    node_version="$(node --version 2>/dev/null || true)"
    node_version="${node_version#v}"
  fi
  if [ -z "$node_version" ]; then
    log "warning: cannot determine image Node version, skipping fnm link"
    return 0
  fi

  mkdir -p "$fnm_dir/node-versions" "$fnm_dir/aliases"
  for inst in "$fnm_dir"/node-versions/*/installation; do
    if [ -L "$inst" ] && [ ! -e "$inst" ]; then
      rm -f "$inst"
      rmdir "$(dirname "$inst")" 2>/dev/null || true
    fi
  done

  inst="$fnm_dir/node-versions/v$node_version/installation"
  mkdir -p "$(dirname "$inst")"
  if [ -L "$inst" ] || [ ! -e "$inst" ]; then
    ln -sfn "/opt/node/v$node_version/installation" "$inst"
  fi

  # -e follows the link, so a default pointing at a removed version counts as missing
  if [ ! -e "$fnm_dir/aliases/default" ] && command -v fnm >/dev/null; then
    rm -f "$fnm_dir/aliases/default"
    fnm default "$node_version" >/dev/null || log "warning: fnm default $node_version failed"
  fi
}

user_half() {
  # covers --user runs where the root half never ran
  mkdir -p "${CONFIG_DIRS[@]}" "${CACHE_DIRS[@]}" 2>/dev/null || true
  link_ssh
  mkdir -p "$(dirname "${GIT_CONFIG_GLOBAL:-/config/git/config}")"
  touch "${GIT_CONFIG_GLOBAL:-/config/git/config}"

  link_fnm_node
  [ "${KEYRING:-0}" = 1 ] && start_keyring

  register-mcp || log "register-mcp failed; run it manually later"
  # newer claude/t3 from AUTO_UPDATE; a no-op without network when unset
  update-tools || log "update-tools failed; using the image versions"

  if [ "${T3_TELEMETRY:-0}" = 0 ]; then
    export T3CODE_TELEMETRY_ENABLED=false T3CODE_OTEL_SDK_DISABLED=true
  fi

  if [ "${1:-}" = serve ]; then
    log "the pairing link in the t3 banner uses the container bridge IP; run 'docker exec <container> pair' instead"
    exec t3 serve --host "${T3CODE_HOST:-0.0.0.0}" --port "${T3CODE_PORT:-3773}" "$WORKSPACE"
  fi
  exec "$@"
}

if [ "$(id -u)" = 0 ]; then
  root_half "$@"
fi
user_half "$@"
